baseURL = 'https://joysankar-astro.github.io/astro-notes/'
languageCode = 'en-us'
title = 'Astro-Notes'
theme = "hugo-book"

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1
  
[menu]
[[menu.home]]
  name = "Fermi-LAT Analysis"
  url = "/docs/fermi-lat-analysis/"
  weight = 1
  
[params]
  BookTheme = 'auto'
  BookToC = true

